apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalog-test
  description: Repo vazio
  labels:
    example.com/custom: custom_label_value
  tags:
    - yaml
    - google
  links:
    - url: https://backstage.io/docs/getting-started/app-custom-theme/
      title: ????
      icon: datadog
    - url: https://backstage.io/docs/getting-started/app-custom-theme/
      title: mac100
  annotations:
      backstage.io/techdocs-ref: https://github.com/reb27/catalog-test/blob/master/README.md
spec:
  type: library
  lifecycle: development
  owner: reb27
